# Generated by Django 5.0.6 on 2024-05-13 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('in progress', 'in progress')], default='pending', max_length=20)),
                ('task_assigned_date', models.DateTimeField(auto_now_add=True)),
                ('task_completed_date', models.DateTimeField(blank=True, null=True)),
                ('task_deadline', models.DateTimeField()),
                ('task_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('task_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
